### ISSUE TITLE
Write tidelift funding retriever

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/funder-finder#14]
As suggested by John Speed. Like numfocus, I wonder if we'd only be able to retrieve a boolean "is it sponsored by tidelift or not" value

**Comment by jspeed-meyers** [comment]
I'll take a shot at this later this week unless you direct me to another issue.

**Comment by jmelot** [comment]
Sounds like a plan!

**Comment by jspeed-meyers** [comment]
This repo has a tidelift badge: https://github.com/pypa/setuptools

Can use for testing purposes
