### ISSUE TITLE
Add GSOC retriever?

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/funder-finder#22]
So it looks like as well as some labor GSOC supports projects with a little bit of funding (maybe not enough to be worth considering for this project especially since it seems to just be a mentorship stipened): 

```
Organizations. At the end of the Program, Organizations may receive (i) a $500 USD stipend 
per GSoC Contributor mentored by making a request through the form provided by Google by 
July 1, 2023. Google is not required to pay amounts requested after this date. 
```
From https://summerofcode.withgoogle.com/rules

Anyway I thought it might be interesting to add them a source as well, but perhaps that's outside the scope of what we're really trying to do here. What do you think @jspeed-meyers ?

**Comment by jspeed-meyers** [comment]
It seems within scope to me :) Let's do it.

**Comment by jmelot** [comment]
As I look at it more closely I think this one will be a bit tricky... but I am game/brought this on myself! I will look at it before we talk in Jan, unless there is something you think is more helpful for me to work on.

**Comment by jspeed-meyers** [comment]
No, no, it's worth trying out. We could also take to the GSOC organization (lots of my current colleagues are ex-Googlers) and see if the GSOC has advice for us.

**Comment by jmelot** [comment]
Glorious! Sounds good 🚀

**Comment by jmelot** [comment]
Did you ever hear back from her? If not, maybe I'll give it another week and then start muddling my way toward an initial version of this

**Comment by jspeed-meyers** [comment]
I was delinquent, I think. I didn't send the email yet. Let me send it ASAP.

**Comment by jmelot** [comment]
👍 No great rush!

**Comment by jspeed-meyers** [comment]
Sent!

**Comment by jspeed-meyers** [comment]
What Stephanie recommended: [g.co/gsoc](http://g.co/gsoc)
