### ISSUE TITLE
Why Not Pin the Dependencies in Requirements.txt?

### ISSUE THREAD

**Issue by jspeed-meyers** [georgetown-cset/funder-finder#33]
Mainly curious.

Pinning these could help with reproducibility across machines.

I'm glad to pin them with a PR. And as long as dependabot is activated (it it right now?), then we would get updates.

**Comment by jmelot** [comment]
I don't think I have a super compelling reason for not doing this. I'm all for it! I've just enabled dependabot security alerts as well.
