### ISSUE TITLE
Define schema for metadata to be retrieved from each funding source

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/funder-finder#8]
I think it would be nice to define what metadata we'd like to collect from each funding source, so we can standardize our scripts' output. Right now the Open Collective script is just retrieving number of contributors and total funding, but we probably want to collect more metadata where it is available.

(I'll come back with more concrete thoughts about what I'd like to see here later, but happy to add in whatever else you think would be useful as well)

**Comment by jspeed-meyers** [comment]
Perhaps this issue is easiest to address synchronously? We could do a Google meet early in the new year or pair program at a coffee shop.

**Comment by jmelot** [comment]
Either option sounds good, maybe we can discuss this related issue as well https://github.com/georgetown-cset/funder-finder/issues/24 . Let me know when you're free, Thursdays and Saturdays are very difficult for me to schedule right now but I generally have more availability other days, especially in the afternoons.

**Comment by jspeed-meyers** [comment]
Hmm, let's do a Friday then. January 6th looks good. I can send you a google meet invite, if that works.

**Comment by jmelot** [comment]
Sounds good! I'm currently available anytime outside of 10-11 and 1-1:30 on the 6th. Thanks for setting it up!

**Comment by jspeed-meyers** [comment]
Invite sent!

**Comment by jspeed-meyers** [comment]
Jennifer and I talked and this is a starting schema:

```json
{
"type": string,
"funding_type": string,
"is_funded": bool,
"num_contributors": int,
"total_funding_usd": int,
"contributors": [{
        "contributor_name": string,
        "amount_received_usd": int,
        "is_affiliated": bool
        }],
"contributions": [{
        "date_contribution_made": YYYY-MM-DD,
        "amount_recieved_usd": int,
        "contributor_name": string,
         }],
"date_of_data_collection": YYYY-MM-DD,
}
```

- potential types include: "open-collective", "numfocus", "github"
- for "github" type, there are two funding types: "repo_contributors", "repo_org"

Open thread:

- Should the wrapper script handled `type` and `isFunded` or should each retriever handle this?

**Comment by jspeed-meyers** [comment]
@jmelot, should we close this issue? We could put this schema in a secondary README only intended for project developers rather than project users. wdyt?

**Comment by jmelot** [comment]
I think you're right - actually this is already documented [here](https://github.com/georgetown-cset/funder-finder/blob/main/funderfinder/sources/_finder.py#L37) so I think I'll just close it. Thanks for the push to clean up the issue list!
